export type NotificationType =
  | 'REQUEST_CREATED'
  | 'REQUEST_ASSIGNED'
  | 'REQUEST_SCHEDULED'
  | 'REQUEST_SCHEDULE_ACCEPTED'
  | 'REQUEST_SCHEDULE_REJECTED'
  | 'REQUEST_VISIT_REPORTED'
  | 'REQUEST_COMPLETED'
  | 'REQUEST_RATED'
  | 'REQUEST_CANCELLED'
  | 'RENT_DUE'
  | 'RENT_OVERDUE'
  | 'CONTRACT_EXPIRING'
  | 'CONTRACT_ACTIVATED'
  | 'CONTRACT_AWAITING_OWNER_REVIEW'
  | 'TENANT_DRAFT_LEASE_PENDING_OWNER'
  | 'TENANT_LEASE_REJECTED_BY_OWNER'
  | 'TENANT_LEASE_AMENDED_BY_OWNER'
  | 'TENANT_LEASE_OWNER_APPROVAL_DENIED'
  | 'ACCOUNTANT_LEASE_OWNER_APPROVAL_DENIED'
  | 'CONTRACT_TERMINATION_REQUESTED'
  | 'TENANT_CONTRACT_TERMINATION_REQUESTED'
  | 'CONTRACT_TERMINATION_APPROVED'
  | 'CONTRACT_TERMINATION_REJECTED'
  | 'CONTRACT_RENEWAL_REQUESTED'
  | 'TENANT_CONTRACT_RENEWAL_REQUESTED'
  | 'CONTRACT_RENEWAL_APPROVED'
  | 'CONTRACT_RENEWAL_REJECTED'
  | 'ACCOUNTANT_CONTRACT_RENEWAL_APPROVED'
  | 'ACCOUNTANT_CONTRACT_RENEWAL_REJECTED'
  | 'PAYMENT_RECEIVED'
  | 'PAYROLL_GENERATED'
  | 'PAYROLL_SUBMITTED'
  | 'PAYROLL_APPROVED'
  | 'PAYROLL_REJECTED'
  | 'PAYROLL_MARKED_PAID'
  | 'PAYROLL_HR_DEDUCTION_APPLIED'
  | 'PAYSLIP_AVAILABLE'
  | 'SALARY_ADVANCE_REQUESTED'
  | 'SALARY_ADVANCE_APPROVED'
  | 'SALARY_ADVANCE_REJECTED'
  | 'SALARY_ADVANCE_DEDUCTED'
  | 'HR_DEDUCTION_SENT_TO_ACCOUNTANT'
  | 'HR_DEDUCTION_APPROVED'
  | 'HR_DEDUCTION_REJECTED'
  | 'LEAVE_REQUEST_SUBMITTED'
  | 'LEAVE_REQUEST_APPROVED'
  | 'LEAVE_REQUEST_REJECTED'
  | 'LEAVE_BALANCE_LOW'
  | 'FINANCE_ALERT'
  | 'BUDGET_THRESHOLD_EXCEEDED'
  | 'VACANCY_PUBLISHED'
  | 'RENTAL_INQUIRY_RECEIVED'
  | 'INSPECTION_COMPLETED'
  | 'RENT_GRACE_PERIOD_ENDING'
  | 'MAINTENANCE_UPDATE'
  | 'MAINTENANCE_REQUEST_OVERDUE'
  | 'INVENTORY_LOW_STOCK'
  | 'NEW_LOGIN_ALERT'
  | 'ACCOUNT_LOCKED'
  | 'DOCUMENT_EXPIRY_WARNING'
  | 'MAINTENANCE_PROVIDER_ASSIGNED'
  | 'MAINTENANCE_PROVIDER_UNASSIGNED'
  | 'OWNER_STATEMENT'
  | 'PROPERTY_LINKED_TO_OWNER'
  | 'UNIT_ADDED_TO_OWNER_PROPERTY'
  | 'TENANT_REGISTERED_ON_OWNER_PROPERTY'
  | 'GENERAL'
  | 'MAINTENANCE_CONTRACT_AWAITING_OWNER_REVIEW'
  | 'MAINTENANCE_CONTRACT_APPROVED'
  | 'MAINTENANCE_CONTRACT_REJECTED'
  | 'MAINTENANCE_CONTRACT_PAYMENT_RECEIVED'
  | 'MAINTENANCE_CONTRACT_TERMINATION_REQUESTED'
  | 'MAINTENANCE_CONTRACT_TERMINATION_APPROVED'
  | 'MAINTENANCE_CONTRACT_TERMINATION_REJECTED'
  | 'MAINTENANCE_CONTRACT_RENEWAL_REQUESTED'
  | 'MAINTENANCE_CONTRACT_RENEWAL_APPROVED'
  | 'MAINTENANCE_CONTRACT_RENEWAL_REJECTED'
  | 'MAINTENANCE_CONTRACT_INVOICE_ISSUED'
  | 'MAINTENANCE_CONTRACT_PAYMENT_SCHEDULED'
  | 'MAINTENANCE_CONTRACT_PAYMENT_DUE_SOON'
  | 'MAINTENANCE_CONTRACT_PAYMENT_DUE_TODAY'
  | 'COMPLAINT_SUBMITTED'
  | 'COMPLAINT_REPLY_RECEIVED'
  | 'COMPLAINT_CLOSED'
  | 'COMPLAINT_RATED'
  | 'CONTRACT_EXPIRING_SOON'
  | 'NO_RENEWAL_INTENT_SUBMITTED'
  | 'DEPOSIT_RETURNED'
  | 'UNIT_DAMAGE_REPORTED'
  | 'DAMAGE_RECEIPT_SUBMITTED'
  | 'DAMAGE_PAYMENT_CONFIRMED'
  | 'UNIT_CLEARED'
  | 'INSPECTION_SCHEDULED';

/**
 * Structured i18n payload sent by the backend so the frontend renders the
 * localized title/body from translation files instead of trusting raw strings.
 * Shape: { titleKey?, bodyKey?, vars? }.
 */
export interface NotificationParams {
  titleKey?: string;
  bodyKey?: string;
  vars?: Record<string, string | number | boolean | null>;
  /** Inbox deep-link hints (persisted beside i18n keys). */
  contractId?: number;
  maintenanceContractId?: number;
  unitId?: number;
  tenantId?: number;
  propertyId?: number;
  /** Complaint-originated maintenance request flags. */
  fromComplaint?: boolean;
  complaintId?: number;
  invoiceId?: number;
  listingId?: number;
  expenseId?: number;
  inspectionId?: number;
  inquiryId?: number;
  /** Backend deep-link route (e.g. HR payroll screens). */
  route?: string;
  requestId?: number;
  color?: string;
}

export interface AppNotification {
  id: number;
  type: NotificationType;
  title: string;
  message: string;
  actorUserId?: number;
  actorDisplayName?: string;
  propertyId?: number;
  requestId?: number;
  read: boolean;
  readAt?: string;
  createdAt: string;
  /** Present when the notification was created via the localized flow. */
  params?: NotificationParams | null;
}
