package com.propertymanagement.modules.notification;

public enum NotificationType {
    REQUEST_CREATED,
    REQUEST_ASSIGNED,
    REQUEST_SCHEDULED,
    REQUEST_SCHEDULE_ACCEPTED,
    REQUEST_SCHEDULE_REJECTED,
    REQUEST_VISIT_REPORTED,
    REQUEST_COMPLETED,
    REQUEST_RATED,
    REQUEST_CANCELLED,
    RENT_DUE,
    RENT_OVERDUE,
    CONTRACT_EXPIRING,
    CONTRACT_ACTIVATED,
    PAYMENT_RECEIVED,
    PAYROLL_GENERATED,
    FINANCE_ALERT,
    MAINTENANCE_UPDATE,
    OWNER_STATEMENT,
    GENERAL
}
