-- V10: Add audit columns (actor + timestamps) for major business tables

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE owners ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE owners ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE owners ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE owners ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE properties ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE floors ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE floors ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE floors ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE floors ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE units ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE units ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE maintenance_categories ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE maintenance_categories ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE maintenance_categories ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE maintenance_categories ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE maintenance_requests ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE maintenance_requests ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE maintenance_requests ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE maintenance_requests ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE request_attachments ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE request_attachments ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE request_attachments ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE request_attachments ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE visit_reports ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE visit_reports ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE visit_reports ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE visit_reports ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE visit_report_items ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE visit_report_items ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE visit_report_items ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE visit_report_items ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS created_on TIMESTAMP DEFAULT NOW() NOT NULL;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS modified_by BIGINT;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP DEFAULT NOW() NOT NULL;
