package com.propertymanagement.modules.lookup;

public enum LookupType {
    COUNTRY,
    CITY,
    UNIT_TYPE,
    PROPERTY_TYPE,
    PROPERTY_STATUS,
    FLOOR_TYPE,
    PAYMENT_METHOD,
    PAYMENT_FREQUENCY,
    CONTRACT_TYPE,
    CONTRACT_STATUS,
    TERMINATION_REASON,
    JOB_TITLE,
    UNIT_OF_MEASURE,
    VIOLATION_STATUS,
    VIOLATION_SEVERITY,
    VIOLATION_TYPE,
    COMPLAINT_STATUS,
    COMPLAINT_PRIORITY,
    COMPLAINT_TYPE,
    INSPECTION_TYPE,
    INSPECTION_CONDITION
}
